// <auto-generated />
using BookShop.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookShop.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("BookShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListPrice")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Price100")
                        .HasColumnType("int");

                    b.Property<int>("Price50")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "小明",
                            CategoryId = 1,
                            Description = "小明寫的 ",
                            ImageUrl = "",
                            ListPrice = 99,
                            Price = 90,
                            Price100 = 80,
                            Price50 = 85,
                            Title = "A 書"
                        },
                        new
                        {
                            Id = 2,
                            Author = "小白",
                            CategoryId = 2,
                            Description = "小白寫的 ",
                            ImageUrl = "",
                            ListPrice = 40,
                            Price = 30,
                            Price100 = 20,
                            Price50 = 25,
                            Title = "B 書"
                        },
                        new
                        {
                            Id = 3,
                            Author = "小紅",
                            CategoryId = 3,
                            Description = "小紅寫的 ",
                            ImageUrl = "",
                            ListPrice = 55,
                            Price = 50,
                            Price100 = 35,
                            Price50 = 40,
                            Title = "C 書"
                        },
                        new
                        {
                            Id = 4,
                            Author = "小成",
                            CategoryId = 1,
                            Description = "小成寫的 ",
                            ImageUrl = "",
                            ListPrice = 70,
                            Price = 65,
                            Price100 = 55,
                            Price50 = 60,
                            Title = "D 書"
                        },
                        new
                        {
                            Id = 5,
                            Author = "小劉",
                            CategoryId = 2,
                            Description = "小劉寫的 ",
                            ImageUrl = "",
                            ListPrice = 30,
                            Price = 27,
                            Price100 = 20,
                            Price50 = 25,
                            Title = "E 書"
                        },
                        new
                        {
                            Id = 6,
                            Author = "小郭",
                            CategoryId = 3,
                            Description = "小郭寫的 ",
                            ImageUrl = "",
                            ListPrice = 25,
                            Price = 23,
                            Price100 = 20,
                            Price50 = 22,
                            Title = "F 書"
                        });
                });

            modelBuilder.Entity("BookShop.Models.Product", b =>
                {
                    b.HasOne("BookShop.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
